services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_PATH}/jellyfin:/config
      - ${DATA_PATH}/media:/data/media
    networks:
      - home_net
    ports:
      - 8096:8096 # LEAVE OPEN FOR LOCAL SMART TV
    labels:
      caddy: ${DOMAIN}
      caddy.handle: /jellyfin*
      caddy.handle.reverse_proxy: "{{upstreams 8096}}"
    restart: unless-stopped
networks:
  media_net:
    name: home_net
    external: true    