services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HOMEPAGE_VAR_DOMAIN=${DOMAIN}
      - HOMEPAGE_ALLOWED_HOSTS=${DOMAIN},${TS_IP},${LOCAL_IP}
    volumes:
      - ${CONF_PATH}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CLOUD_PATH}:/mnt/cloud
    networks:
      - home_net
    labels:
      # Sets homepage as the default root landing page
      caddy: ${DOMAIN}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    group_add:
      - "985"  
    restart: unless-stopped

networks:
  home_net:
    external: true
