services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    user: "1000:985"
    ports:
      - 3000:3000
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HOMEPAGE_VAR_DOMAIN=${DOMAIN}
      - HOMEPAGE_ALLOWED_HOSTS=${DOMAIN},${TS_IP}:3000,${LOCAL_IP}:3000
    volumes:
      - ${CONF_PATH}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CLOUD_PATH}:/mnt/cloud
    networks:
      - home_net
    labels:
      # Sets homepage as the default root landing page
      caddy: ${DOMAIN}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    group_add:
      - "985"  
    restart: unless-stopped
  dashy:
    # The image to pull + version. Can use `ghcr.io/lissy93/dashy` instead
    image: lissy93/dashy:latest
    # Optional container name
    container_name: dashy
    # Port to serve on (keep container port (second one) as 8080)
    ports:
      - 6006:8080
    networks:
      - home_net  
    # Mount a directory containing your conf.yml and any other assets
    volumes:
      - ${CONF_PATH}/dashy:/app/user-data
    # Add any env vars for server here, if needed
    environment:
      - NODE_ENV=production
    # Auto-start the container on boot
    restart: unless-stopped
    # Healthcheck to determine when container healthy
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck.js']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
networks:
  home_net:
    external: true
