services:
  deemix:
    image: ghcr.io/bambanah/deemix:latest
    container_name: deemix
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_PATH}/deemix:/config
      - ${DATA_PATH}:/data
    ports:
      - 6595:6595
    networks:
      - home_net
    restart: unless-stopped

  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - ${CONF_PATH}/slskd:/app/config
      - ${DATA_PATH}:/data
    ports:
      - 5030:5030
    networks:
      - home_net
    restart: unless-stopped

  lidarr-downloader:
    image: angrido/lidarr-downloader:latest
    container_name: lidarr-downloader
    ports:
      - 5005:5000
    volumes:
      - ${CONF_PATH}/lidarr-downloader:/config
      - ${DATA_PATH}:/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - LIDARR_URL=http://lidarr:8686
      - LIDARR_API_KEY=${LIDARR_API_KEY}
      - DOWNLOAD_PATH=/data/downloads/youtube
      - LIDARR_PATH=/data/media/music
    networks:
      - home_net
    restart: unless-stopped

networks:
  home_net:
    name: home_net
    external: true
