services:
  caddy_proxy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy_proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=home_net
    networks:
      - home_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock:ro
      - ${CONF_PATH}/caddy:/data
    restart: unless-stopped

networks:
  home_net:
    external: true
