services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_PATH}/lidarr:/config
      - ${DATA_PATH}:/data
    ports:
      - 8686:8686  
    networks:
      - home_net
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_PATH}/prowlarr:/config
    networks:
      - home_net
    ports:
      - 9696:9696 # Temporary
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_PATH}/radarr:/config
      - ${DATA_PATH}:/data
    networks:
      - home_net
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_PATH}/sonarr:/config
      - ${DATA_PATH}:/data
    networks:
      - home_net
    ports:
      - 8989:8989
    restart: unless-stopped
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_PATH}/jellyseerr:/app/config
    networks:
      - home_net
    ports:
      - 5055:5055
    restart: unless-stopped
  mixarr:
    image: ghcr.io/aquantumofdonuts/mixarr:latest
    container_name: mixarr
    ports:
      - "3443:443"  # HTTPS Access
      - "3010:3010" # Web UI (HTTP)
    volumes:
      - ${CONF_PATH}/mixarr:/data
    environment:
      - SESSION_SECRET=GGGGAGAGAGGGEGEGXCYCYYVUBINUEVBAFVDS
      - BASE_URL=https://${TS_IP}:3443
    restart: unless-stopped
networks:
  home_net:
    name: home_net
    external: true        
