services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    user: "${PUID}:${PGID}"
    environment:
      - TZ=${TZ}
    ports:
      - 8345:80
    volumes:
      - ${DATA_PATH}:/srv
      - ${CONF_PATH}/filebrowser/filebrowser.db:/filebrowser.db
      - ${CONF_PATH}/filebrowser/settings.json:/config/settings.json
    networks:
      - media_net
    labels:
      caddy: ${DOMAIN}
      caddy.handle_path: /files*
      caddy.handle_path.reverse_proxy: "{{upstreams 80}}"
    restart: unless-stopped
  webdav:
    image: hacdias/webdav
    restart: always
    ports:
      - "8660:8080"
    volumes:
      - ${DATA_PATH}:/data
      - ${CONF_PATH}/webdav/config.yml:/config.yml
    command: -c /config.yml
networks:
  media_net:
    external: true
